plugins:
  enabled: []
_config_version: 39
agent: {}
model:
  default: minimax/minimax-m3:free
  provider: openrouter-free
skills:
  external_dirs:
    - ~/.hermes/skills
fallback_providers:
  - provider: openrouter-free
    model: minimax/minimax-m3:free
  - provider: openrouter-free
    model: inclusionai/ling-3.0-flash-fin:free
  - provider: openrouter-free
    model: thinkingmachines/inkling:free
  - provider: opencode-zen
    model: ling-3.0-flash-fin-free
  - provider: nous
    model: meituan/longcat-2.0:free
